# AUTOGENERATED! DO NOT EDIT! File to edit: ../diffedit.ipynb.

# %% auto 0
__all__ = ['torch_device', 'im']

# %% ../diffedit.ipynb 6
from base64 import b64encode

import os
import numpy
import torch
from diffusers import AutoencoderKL, LMSDiscreteScheduler, UNet2DConditionModel
from huggingface_hub import notebook_login
from fastai.vision.all import *

from IPython.display import HTML
from matplotlib import pyplot as plt
from pathlib import Path
from PIL import Image
from torch import autocast
from torchvision import transforms as tfms
from tqdm.auto import tqdm
from transformers import CLIPTextModel, CLIPTokenizer


import tsensor
from lolviz import *


import logging

torch_device = "cuda" if torch.cuda.is_available() else "cpu"
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)
logging.disable(logging.WARNING)
torch.manual_seed(1);

# %% ../diffedit.ipynb 18
im = Image.open('imgs/IMG_4104_512.jpg')
